Repository dnd-side-project/dnd-11th-5-backend, pull requests merged in 2024-07, with the labels that each got.

#2 env: 프로젝트 초기 셋팅
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  http/hello.http
  settings.gradle
  src/main/java/com/example/demo/DemoApplication.java
  src/main/java/com/example/demo/common/ApiResponse.java
  src/main/java/com/example/demo/common/aop/A.java
  src/main/java/com/example/demo/common/config/JpaAuditingConfig.java
  src/main/java/com/example/demo/common/domain/BaseEntity.java
  src/main/java/com/example/demo/common/error/ErrorCode.java
  src/main/java/com/example/demo/common/error/ErrorResponse.java
  src/main/java/com/example/demo/common/error/GlobalExceptionHandler.java
  src/main/java/com/example/demo/common/error/exception/CustomException.java
  src/main/java/com/example/demo/common/jwt/J.java
  src/main/java/com/example/demo/common/util/U.java
  src/main/java/com/example/demo/hello/controller/HelloController.java
  src/main/resources/application.yml
  src/test/java/com/example/demo/ControllerTestSupport.java
  src/test/java/com/example/demo/DemoApplicationTests.java
  src/test/java/com/example/demo/hello/controller/HelloControllerTest.java
Labels: env

#8 env: project name, artifacts, group 명 변경
  build.gradle
  settings.gradle
  src/main/java/com/example/demo/common/aop/A.java
  src/main/java/com/example/demo/common/jwt/J.java
  src/main/java/com/example/demo/common/util/U.java
  src/main/java/com/odiga/fiesta/DemoApplication.java
  src/main/java/com/odiga/fiesta/common/ApiResponse.java
  src/main/java/com/odiga/fiesta/common/aop/A.java
  src/main/java/com/odiga/fiesta/common/config/JpaAuditingConfig.java
  src/main/java/com/odiga/fiesta/common/domain/BaseEntity.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/common/error/ErrorResponse.java
  src/main/java/com/odiga/fiesta/common/error/GlobalExceptionHandler.java
  src/main/java/com/odiga/fiesta/common/error/exception/CustomException.java
  src/main/java/com/odiga/fiesta/common/jwt/J.java
  src/main/java/com/odiga/fiesta/common/util/U.java
  src/main/java/com/odiga/fiesta/hello/controller/HelloController.java
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/DemoApplicationTests.java
  src/test/java/com/odiga/fiesta/hello/controller/HelloControllerTest.java
Labels: type: env

#9 feat: 테스트 환경 구성
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/IntegrationTestSupport.java
  src/test/java/com/odiga/fiesta/MockTestSupport.java
  src/test/java/com/odiga/fiesta/RepositoryTestSupport.java
Labels: type: feat

#11 feat: Swagger 설정
  build.gradle
  src/main/java/com/odiga/fiesta/common/config/SwaggerConfig.java
Labels: type: env

#13 feat: QueryDsl 설정
  .gitignore
  build.gradle
  src/main/java/com/odiga/fiesta/common/config/QueryDslConfig.java
Labels: type: env

#15 feat: ExceptionHandler 에서 404 에러 처리 추가
  src/main/java/com/odiga/fiesta/common/error/GlobalExceptionHandler.java
  src/test/java/com/odiga/fiesta/hello/controller/HelloControllerTest.java
Labels: type: feat

#16 feat: http request 에 대한 logging 구현
  src/main/java/com/odiga/fiesta/common/filter/LogFilter.java
  src/test/java/com/odiga/fiesta/common/filter/LogFilterTest.java
Labels: type: env

#18 env: Security 기본 설정
  build.gradle
  src/main/java/com/odiga/fiesta/common/config/CorsMvcConfig.java
  src/main/java/com/odiga/fiesta/common/config/SecurityConfig.java
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
Labels: type: env

#20 feat: pr ci 구현
  .github/workflows/pr-ci.yml
  build.gradle
  lombok.config
Labels: type: feat
