Repository dnd-side-project/dnd-11th-5-backend, pull requests merged in 2024-08, with the labels that each got.

#26 feat: `PageResponse` 구현
  src/main/java/com/odiga/fiesta/common/ApiResponse.java
  src/main/java/com/odiga/fiesta/common/PageResponse.java
Labels: type: feat

#29 feat: 페스티벌 정적 데이터 관련 API 구현
  build.gradle
  src/main/java/com/odiga/fiesta/common/BasicResponse.java
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/festival/domain/Category.java
  src/main/java/com/odiga/fiesta/festival/domain/Companion.java
  src/main/java/com/odiga/fiesta/festival/domain/Mood.java
  src/main/java/com/odiga/fiesta/festival/domain/Priority.java
  src/main/java/com/odiga/fiesta/festival/dto/response/CategoryResponse.java
  src/main/java/com/odiga/fiesta/festival/dto/response/CompanionResponse.java
  src/main/java/com/odiga/fiesta/festival/dto/response/MoodResponse.java
  src/main/java/com/odiga/fiesta/festival/dto/response/PriorityResponse.java
  src/main/java/com/odiga/fiesta/festival/repository/CategoryRepository.java
  src/main/java/com/odiga/fiesta/festival/repository/CompanionRepository.java
  src/main/java/com/odiga/fiesta/festival/repository/MoodRepository.java
  src/main/java/com/odiga/fiesta/festival/repository/PriorityRepository.java
  src/main/java/com/odiga/fiesta/festival/service/CategoryService.java
  src/main/java/com/odiga/fiesta/festival/service/CompanionService.java
  src/main/java/com/odiga/fiesta/festival/service/MoodService.java
  src/main/java/com/odiga/fiesta/festival/service/PriorityService.java
  src/main/java/com/odiga/fiesta/hello/controller/HelloController.java
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
  src/test/java/com/odiga/fiesta/festival/service/CategoryServiceTest.java
  src/test/java/com/odiga/fiesta/festival/service/CompanionServiceTest.java
  src/test/java/com/odiga/fiesta/festival/service/MoodServiceTest.java
  src/test/java/com/odiga/fiesta/festival/service/PriorityServiceTest.java
Labels: type: feat

#35 feat: `Keyword` 도메인 구현
  src/main/java/com/odiga/fiesta/keyword/domain/Keyword.java
  src/main/java/com/odiga/fiesta/keyword/repository/KeywordRepository.java
Labels: type: feat

#37 feat: 주요 엔티티 생성
  src/main/java/com/odiga/fiesta/festival/domain/Festival.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalRepository.java
  src/main/java/com/odiga/fiesta/review/domain/Review.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewRepository.java
  src/main/java/com/odiga/fiesta/user/domain/User.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/LocalUser.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/OauthUser.java
  src/main/java/com/odiga/fiesta/user/domain/repository/UserRepository.java
  src/main/java/com/odiga/fiesta/user/oauth/OauthProvider.java
  src/main/resources/db/migration/V4__drop_activity_alter_festival.sql
  src/main/resources/db/migration/V5__alter_user_and_festival.sql
Labels: type: feat

#40 feat: 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/odiga/fiesta/common/config/S3Config.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/common/error/exception/s3/InvalidExtensionException.java
  src/main/java/com/odiga/fiesta/common/error/exception/s3/InvalidImageException.java
  src/main/java/com/odiga/fiesta/common/error/exception/s3/UploadFailException.java
  src/main/java/com/odiga/fiesta/s3/service/S3Service.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/OauthUser.java
  src/main/java/com/odiga/fiesta/user/domain/oauth/OauthProvider.java
  src/main/java/com/odiga/fiesta/user/oauth/OauthProvider.java
  src/test/java/S3MockConfig.java
  src/test/java/com/odiga/fiesta/s3/service/S3ServiceTest.java
Labels: type: feat

#42 refactor: 정적 데이터 도메인 분리
  src/main/java/com/odiga/fiesta/category/domain/Category.java
  src/main/java/com/odiga/fiesta/category/repository/CategoryRepository.java
  src/main/java/com/odiga/fiesta/companion/domain/Companion.java
  src/main/java/com/odiga/fiesta/companion/repository/CompanionRepository.java
  src/main/java/com/odiga/fiesta/festival/dto/response/CategoryResponse.java
  src/main/java/com/odiga/fiesta/festival/dto/response/CompanionResponse.java
  src/main/java/com/odiga/fiesta/festival/dto/response/MoodResponse.java
  src/main/java/com/odiga/fiesta/festival/dto/response/PriorityResponse.java
  src/main/java/com/odiga/fiesta/festival/service/CategoryService.java
  src/main/java/com/odiga/fiesta/festival/service/CompanionService.java
  src/main/java/com/odiga/fiesta/festival/service/MoodService.java
  src/main/java/com/odiga/fiesta/festival/service/PriorityService.java
  src/main/java/com/odiga/fiesta/mood/domain/Mood.java
  src/main/java/com/odiga/fiesta/mood/repository/MoodRepository.java
  src/main/java/com/odiga/fiesta/priority/domain/Priority.java
  src/main/java/com/odiga/fiesta/priority/repository/PriorityRepository.java
  src/test/java/com/odiga/fiesta/festival/service/CategoryServiceTest.java
  src/test/java/com/odiga/fiesta/festival/service/CompanionServiceTest.java
  src/test/java/com/odiga/fiesta/festival/service/MoodServiceTest.java
  src/test/java/com/odiga/fiesta/festival/service/PriorityServiceTest.java
Labels: type: refactor

#52 feat: 카테고리 테이블 수정사항 반영
  src/main/java/com/odiga/fiesta/category/domain/Category.java
  src/main/java/com/odiga/fiesta/festival/dto/response/CategoryResponse.java
  src/main/java/com/odiga/fiesta/festival/service/CategoryService.java
  src/main/resources/db/migration/V7__alter_category.sql
Labels: type: feat

#54 feat: 페스티벌 북마크 등록/해제 구현
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalBookmark.java
  src/main/java/com/odiga/fiesta/festival/dto/request/FestivalFilterRequest.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalBookmarkResponse.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalBookmarkRepository.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalBookmarkService.java
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalBookmarkServiceTest.java
Labels: type: feat

#62 feat: HOT 한 페스티벌 조회 api 구현
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/festival/dto/projection/FestivalWithBookmarkCountAndSido.java
  src/main/java/com/odiga/fiesta/festival/dto/projection/FestivalWithSido.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalBasic.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalInfo.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalInfoWithBookmark.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalThisWeekResponse.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepository.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
Labels: type: feat, safe to test

#70 hotfix: 테이블 이름 인식 못하는 오류 수정
  src/main/java/com/odiga/fiesta/sido/domain/Sido.java
  src/main/resources/db/migration/V8__change_table_name.sql
Labels: 🔥 type: hotfix, safe to test

#71 feat: 방문일지 생성 api 구현
  src/main/java/com/odiga/fiesta/common/BasicResponse.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/common/util/FileUtils.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalImageRepository.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/main/java/com/odiga/fiesta/log/controller/LogController.java
  src/main/java/com/odiga/fiesta/log/domain/Log.java
  src/main/java/com/odiga/fiesta/log/domain/LogImage.java
  src/main/java/com/odiga/fiesta/log/dto/request/LogCreateRequest.java
  src/main/java/com/odiga/fiesta/log/dto/response/LogIdResponse.java
  src/main/java/com/odiga/fiesta/log/service/LogService.java
  src/main/resources/db/migration/V9__alter_log.sql
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/log/controller/LogControllerTest.java
  src/test/java/com/odiga/fiesta/log/service/LogMockServiceTest.java
Labels: safe to test

#73 refactor: UserRepository 위치 변경
  src/main/java/com/odiga/fiesta/log/service/LogService.java
  src/test/java/com/odiga/fiesta/log/service/LogMockServiceTest.java
Labels: type: refactor

#79 hotfix: 테스트 환경에서의 의존성 주입 문제 해결
  build.gradle
  src/main/java/com/odiga/fiesta/common/config/QueryDslConfig.java
  src/main/java/com/odiga/fiesta/common/config/S3Config.java
  src/main/java/com/odiga/fiesta/common/config/SecurityConfig.java
  src/main/java/com/odiga/fiesta/common/config/SwaggerConfig.java
  src/main/java/com/odiga/fiesta/common/config/TimeConfig.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/common/error/GlobalExceptionHandler.java
  src/main/java/com/odiga/fiesta/common/filter/LogFilter.java
  src/main/java/com/odiga/fiesta/common/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/odiga/fiesta/common/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/odiga/fiesta/common/jwt/TokenAuthenticationFilter.java
  src/main/java/com/odiga/fiesta/common/jwt/TokenProvider.java
  src/main/java/com/odiga/fiesta/common/util/FileUtils.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalInfo.java
  src/main/java/com/odiga/fiesta/log/controller/LogController.java
  src/main/java/com/odiga/fiesta/log/service/LogService.java
  src/main/java/com/odiga/fiesta/review/domain/Review.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewRepository.java
  src/main/java/com/odiga/fiesta/s3/service/S3Service.java
  src/main/java/com/odiga/fiesta/user/controller/UserController.java
  src/main/java/com/odiga/fiesta/user/domain/User.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/LocalUser.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/OauthUser.java
  src/main/java/com/odiga/fiesta/user/repository/OauthUserRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserRepository.java
  src/main/java/com/odiga/fiesta/user/service/UserService.java
  src/main/resources/application-test.yml
  src/test/java/com/odiga/fiesta/FiestaApplicationTests.java
  src/test/java/com/odiga/fiesta/IntegrationTestSupport.java
  src/test/java/com/odiga/fiesta/S3MockConfig.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
  src/test/java/com/odiga/fiesta/log/controller/LogControllerTest.java
  src/test/java/com/odiga/fiesta/log/service/LogMockServiceTest.java
  src/test/java/com/odiga/fiesta/log/service/LogServiceTest.java
  src/test/java/com/odiga/fiesta/s3/service/S3ServiceTest.java
Labels: 🔥 type: hotfix, safe to test

#81 fix: pr-ci 수정
  .github/workflows/pr-ci.yml
  .github/workflows/report.yml
Labels: 🔥 type: hotfix

#76 feat: 프로필 생성 기능 구현
  src/main/java/com/odiga/fiesta/common/domain/BaseEntity.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/common/jwt/TokenAuthenticationFilter.java
  src/main/java/com/odiga/fiesta/common/util/NicknameUtils.java
  src/main/java/com/odiga/fiesta/festival/domain/Festival.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalBookmark.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalCategory.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalImage.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalMood.java
  src/main/java/com/odiga/fiesta/log/domain/Log.java
  src/main/java/com/odiga/fiesta/log/domain/LogImage.java
  src/main/java/com/odiga/fiesta/log/domain/LogKeyword.java
  src/main/java/com/odiga/fiesta/review/domain/Review.java
  src/main/java/com/odiga/fiesta/user/controller/UserController.java
  src/main/java/com/odiga/fiesta/user/domain/Role.java
  src/main/java/com/odiga/fiesta/user/domain/User.java
  src/main/java/com/odiga/fiesta/user/domain/UserType.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/OauthUser.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserCategory.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserCompanion.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserMood.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserPriority.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserRole.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserRoleId.java
  src/main/java/com/odiga/fiesta/user/dto/UserRequest.java
  src/main/java/com/odiga/fiesta/user/dto/UserResponse.java
  src/main/java/com/odiga/fiesta/user/repository/UserCategoryRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserCompanionRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserMoodRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserPriorityRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserRoleRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserTypeRepository.java
  src/main/java/com/odiga/fiesta/user/service/UserService.java
  src/main/java/com/odiga/fiesta/user/service/UserTypeService.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V10__alter_role_and_mood.sql
  src/main/resources/db/migration/V11__create_user_role.sql
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
  src/test/java/com/odiga/fiesta/log/service/LogServiceTest.java
Labels: type: feat, safe to test

#84 feat: 페스티벌 상세 조회 응답에 위도,경도 추가
  src/main/java/com/odiga/fiesta/festival/dto/projection/FestivalDetailData.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalDetailResponse.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
Labels: type: feat

#82 feat: 다가오는 페스티벌 조회 API 구현
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalAndLocation.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepository.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
Labels: type: feat

#85 feat: 추천 페스티벌 조회 API 구현
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalUserType.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepository.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalUserTypeRepository.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/main/java/com/odiga/fiesta/user/repository/UserRepository.java
  src/main/resources/db/migration/V12__create_festivalusertype.sql
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
Labels: type: feat

#95 hotfix: 인증 쪽 문제 해결
  build.gradle
  src/main/java/com/odiga/fiesta/auth/domain/AuthUser.java
  src/main/java/com/odiga/fiesta/auth/domain/Authority.java
  src/main/java/com/odiga/fiesta/auth/domain/UserAccount.java
  src/main/java/com/odiga/fiesta/auth/dto/KakaoProfile.java
  src/main/java/com/odiga/fiesta/auth/service/AccountService.java
  src/main/java/com/odiga/fiesta/auth/service/AuthService.java
  src/main/java/com/odiga/fiesta/common/PageResponse.java
  src/main/java/com/odiga/fiesta/common/config/SwaggerConfig.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/common/error/GlobalExceptionHandler.java
  src/main/java/com/odiga/fiesta/common/jwt/TokenAuthenticationFilter.java
  src/main/java/com/odiga/fiesta/common/jwt/TokenProvider.java
  src/main/java/com/odiga/fiesta/common/util/HttpClientUtil.java
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/log/controller/LogController.java
  src/main/java/com/odiga/fiesta/user/controller/UserController.java
  src/main/java/com/odiga/fiesta/user/domain/Role.java
  src/main/java/com/odiga/fiesta/user/domain/User.java
  src/main/java/com/odiga/fiesta/user/domain/UserType.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/LocalUser.java
  src/main/java/com/odiga/fiesta/user/domain/accounts/OauthUser.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserCategory.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserCompanion.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserMood.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserPriority.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserRole.java
  src/main/java/com/odiga/fiesta/user/domain/mapping/UserRoleId.java
  src/main/java/com/odiga/fiesta/user/dto/UserRequest.java
  src/main/java/com/odiga/fiesta/user/dto/UserResponse.java
  src/main/java/com/odiga/fiesta/user/dto/request/SocialLoginRequest.java
  src/main/java/com/odiga/fiesta/user/dto/request/UserRequest.java
  src/main/java/com/odiga/fiesta/user/dto/response/LoginResponse.java
  src/main/java/com/odiga/fiesta/user/dto/response/UserResponse.java
  src/main/java/com/odiga/fiesta/user/repository/OauthUserRepository.java
  src/main/java/com/odiga/fiesta/user/repository/RoleRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserCategoryRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserCompanionRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserMoodRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserPriorityRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserRoleRepository.java
  src/main/java/com/odiga/fiesta/user/repository/UserTypeRepository.java
  src/main/java/com/odiga/fiesta/user/service/UserService.java
  src/main/java/com/odiga/fiesta/user/service/UserTypeService.java
  src/main/java/com/odiga/fiesta/user/util/NicknameUtils.java
  src/main/resources/db/migration/V14__create_new_user_table.sql
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/FiestaApplicationTests.java
  src/test/java/com/odiga/fiesta/IntegrationTestSupport.java
  src/test/java/com/odiga/fiesta/RepositoryTestSupport.java
  src/test/java/com/odiga/fiesta/config/EmbeddedRedisConfig.java
  src/test/java/com/odiga/fiesta/config/QuerydslTestConfig.java
  src/test/java/com/odiga/fiesta/config/S3MockConfig.java
  src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
  src/test/java/com/odiga/fiesta/festival/repository/FestivalRepositoryTest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalBookmarkServiceTest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
  src/test/java/com/odiga/fiesta/log/controller/LogControllerTest.java
Labels: 🔥 type: hotfix

#98 feat: 페스티벌 생성 api 구현
  src/main/java/com/odiga/fiesta/common/config/JsonCustomConfig.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/common/util/FileUtils.java
  src/main/java/com/odiga/fiesta/common/util/NullToEmptyStringSerializer.java
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/festival/domain/Festival.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalCategory.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalImage.java
  src/main/java/com/odiga/fiesta/festival/domain/FestivalMood.java
  src/main/java/com/odiga/fiesta/festival/dto/projection/FestivalDetailData.java
  src/main/java/com/odiga/fiesta/festival/dto/request/FestivalCreateRequest.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalCreateResponse.java
  src/main/java/com/odiga/fiesta/festival/dto/response/FestivalDetailResponse.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/main/java/com/odiga/fiesta/festival/util/CityMapper.java
  src/main/java/com/odiga/fiesta/user/domain/UserType.java
  src/main/java/com/odiga/fiesta/user/repository/UserTypeRepository.java
  src/main/java/com/odiga/fiesta/user/service/UserTypeService.java
  src/main/resources/db/migration/V15__alter_festival_description_length.sql
  src/main/resources/db/migration/V16__alter_festival_user_type_id.sql
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
  src/test/java/com/odiga/fiesta/log/controller/LogControllerTest.java
Labels: type: feat

#100 feat: 내 정보 조회 api 구현
  src/main/java/com/odiga/fiesta/auth/service/AuthService.java
  src/main/java/com/odiga/fiesta/user/controller/UserController.java
  src/main/java/com/odiga/fiesta/user/dto/response/UserInfoResponse.java
  src/main/java/com/odiga/fiesta/user/service/UserService.java
Labels: type: feat, 🔥 우선순위 : 상

#101 feat: 회원 탈퇴 api 구현
  src/main/java/com/odiga/fiesta/auth/service/AuthService.java
  src/main/java/com/odiga/fiesta/user/controller/UserController.java
Labels: type: feat, 🔥 우선순위 : 상

#104 hotfix: 삭제된 이미지 데이터 수정
  src/main/java/com/odiga/fiesta/user/domain/UserType.java
  src/main/java/com/odiga/fiesta/user/dto/request/UserRequest.java
  src/main/java/com/odiga/fiesta/user/dto/response/UserResponse.java
  src/main/java/com/odiga/fiesta/user/service/UserService.java
  src/main/resources/db/migration/V17__create_new_user_type.sql
Labels: 🔥 type: hotfix, 🔥 우선순위 : 상

#107 feat: 가장 많이 선택된 키워드 TOP5 조회
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/dto/ReviewResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewImageResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewKeywordResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/TopReviewResponse.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewRepository.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
Labels: type: feat

#112 refactor: 패키지 구조 정리
  src/main/java/com/odiga/fiesta/auth/service/AuthService.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/user/controller/UserController.java
  src/main/java/com/odiga/fiesta/user/domain/User.java
  src/main/java/com/odiga/fiesta/user/domain/oauth/OauthProvider.java
  src/main/java/com/odiga/fiesta/user/dto/request/ProfileCreateRequest.java
  src/main/java/com/odiga/fiesta/user/dto/request/UserRequest.java
  src/main/java/com/odiga/fiesta/user/dto/response/ProfileCreateResponse.java
  src/main/java/com/odiga/fiesta/user/dto/response/TokenReissueResponse.java
  src/main/java/com/odiga/fiesta/user/dto/response/UserResponse.java
  src/main/java/com/odiga/fiesta/user/service/UserService.java
  src/main/java/com/odiga/fiesta/user/service/UserTypeService.java
  src/main/resources/db/migration/V20__update_static_data.sql
Labels: type: refactor

#116 feat: 리뷰 다건 조회 리팩터링
  src/main/java/com/odiga/fiesta/common/config/QueryDslConfig.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/keyword/domain/Keyword.java
  src/main/java/com/odiga/fiesta/log/dto/response/LogKeywordResponse.java
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/domain/Review.java
  src/main/java/com/odiga/fiesta/review/dto/projection/ReviewData.java
  src/main/java/com/odiga/fiesta/review/dto/projection/ReviewDataWithLike.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewIdResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewImageResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewKeywordResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewUserInfo.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewImageRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewKeywordRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewLikeRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewSortType.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
  src/main/resources/db/migration/V21__change_column_name.sql
  src/test/java/com/odiga/fiesta/config/QuerydslTestConfig.java
  src/test/java/com/odiga/fiesta/log/service/LogServiceTest.java
  src/test/java/com/odiga/fiesta/review/repository/ReviewRepositoryTest.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceTest.java
Labels: type: feat

#118 feat: 모든 리뷰 키워드 조회 api 구현
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewKeywordResponse.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
Labels: type: feat

#120 refactor: 실시간 가장 핫한 리뷰 조회 리팩터링
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/dto/projection/ReviewSimpleData.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewIdResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewKeywordResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewSimpleResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/TopReviewResponse.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceTest.java
Labels: type: refactor

#122 refactor: 페스티벌에서 가장 많이 선택된 리뷰 키워드 조회 리팩터링
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/dto/response/TopReviewKeywordResponse.java
  src/main/java/com/odiga/fiesta/review/dto/response/TopReviewKeywordsResponse.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceTest.java
Labels: type: refactor

#124 feat: 리뷰 생성 API 구현
  build.gradle
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/domain/Review.java
  src/main/java/com/odiga/fiesta/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
  src/test/java/com/odiga/fiesta/review/controller/ReviewControllerTest.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
Labels: type: feat

#125 feat: 리뷰 좋아요 등록/해제 구현
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewLikeResponse.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewLikeRepository.java
  src/main/java/com/odiga/fiesta/review/service/ReviewLikeService.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
  src/test/java/com/odiga/fiesta/ControllerTestSupport.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalBookmarkServiceTest.java
  src/test/java/com/odiga/fiesta/review/service/ReviewLikeServiceTest.java
Labels: type: feat

#129 env: 무중단 배포 구축
  .github/workflows/cd.yml
Labels: type: env

#131 feat: 리뷰 삭제 API 구현
  src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewImageRepository.java
  src/main/java/com/odiga/fiesta/review/repository/ReviewLikeRepository.java
  src/main/java/com/odiga/fiesta/review/service/ReviewService.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
Labels: type: feat

#136 feat: 메소드 실행 시간을 구하기 위한 aop 구현
  src/main/java/com/odiga/fiesta/common/aop/A.java
  src/main/java/com/odiga/fiesta/common/aop/ExeTimer.java
  src/main/java/com/odiga/fiesta/common/aop/ExpTimerImpl.java
Labels: type: feat

#137 refactor: 비효율적인 쿼리 수정
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepository.java
  src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/test/java/com/odiga/fiesta/festival/repository/FestivalRepositoryTest.java
Labels: type: refactor

#138 feat: list 형태로 들어오는 값들의 중복 제거 로직 추가
  src/main/java/com/odiga/fiesta/festival/dto/request/FestivalCreateRequest.java
  src/main/java/com/odiga/fiesta/review/dto/request/ReviewCreateRequest.java
  src/main/java/com/odiga/fiesta/review/dto/request/ReviewUpdateRequest.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
Labels: type: feat

#140 fix: api response 요청 사항 반영
  src/main/java/com/odiga/fiesta/common/config/JsonCustomConfig.java
  src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
  src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
  src/main/java/com/odiga/fiesta/festival/dto/response/RecommendFestivalResponse.java
  src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
  src/main/java/com/odiga/fiesta/review/dto/response/ReviewSimpleResponse.java
  src/main/java/com/odiga/fiesta/user/controller/UserController.java
  src/main/java/com/odiga/fiesta/user/domain/User.java
  src/main/java/com/odiga/fiesta/user/domain/UserType.java
  src/main/java/com/odiga/fiesta/user/dto/response/UserInfoResponse.java
  src/main/java/com/odiga/fiesta/user/dto/response/UserTypeResponse.java
  src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
  src/test/java/com/odiga/fiesta/review/service/ReviewServiceTest.java
Labels: type: fix
